const ws = new WebSocket("wss://urna-mine-verine.wilianzilv.workers.dev/ws");
const got = [];
ws.onmessage = (e) => got.push(JSON.parse(e.data));
await new Promise((r) => (ws.onopen = r));
ws.send(JSON.stringify({ t: "hello", n: "shieldtest" }));
await new Promise((r) => setTimeout(r, 1500));
const welcome = got.find((m) => m.t === "welcome");
const logSets = (welcome?.log || []).filter((m) => m.k === "set");
const inLab = logSets.filter((m) => m.p && m.p[0] >= 88 && m.p[0] <= 119 && m.p[2] >= 49 && m.p[2] <= 80).length;
console.log("welcome log", welcome?.log?.length, "sets", logSets.length, "sets near lab (pre-existing)", inLab);
got.length = 0;
ws.send(JSON.stringify({ t: "w", k: "set", p: [103, 20, 64], b: 0 }));
ws.send(JSON.stringify({ t: "w", k: "set", p: [106, 22, 88], b: 0 }));
ws.send(JSON.stringify({ t: "w", k: "set", p: [60, 46, 60], b: 0 }));
ws.send(JSON.stringify({ t: "chat", m: "/hub.txt" }));
ws.send(JSON.stringify({ t: "chat", m: "/modding" }));
await new Promise((r) => setTimeout(r, 2000));
const echoed = got.filter((m) => m.t === "w").map((m) => m.p.join(","));
console.log("w echoed:", echoed);
console.log("types:", got.map((m) => m.t).join(" "));
console.log("chat:", got.filter((m) => m.t === "chat").map((m) => `${m.n}: ${m.m}`));
ws.close();
process.exit(0);
